name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]  # Trigger this workflow when 'Terraform Plan' workflow completes
    types:
      - completed  # Ensure it runs only after 'Terraform Plan' has completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: account-prod  # Specifies the environment where the job will run

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: "e13ebc52-bd47-4927-a5d9-722eb7465292"
          tenant-id: "4b1732d9-fa44-47bc-ae15-1fac2dca85c6"
          subscription-id: "c57e05a2-b253-4113-8870-0bb21d04023c"

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az account show
    
    - name: Install dependencies
      run: |
        terraform init

    - name: Run Terraform Apply
      run: |
        terraform apply -auto-approve  # Automatically approve the changes
      # env:
        #TF_VAR_some_variable: ${{ secrets.TF_VAR_some_variable }}  # Add any sensitive variables here
        # You can also pass other sensitive credentials using GitHub secrets
