name: Terraform Plan

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull request to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    - name: Azure Login (User-based)
      uses: azure/login@v1
      with:
        # No creds provided, this triggers interactive login (User-based)
        enable_AzureCLI: true

    - name: Show Azure Account
      run: |
        az account show

    - name: Install dependencies
      run: |
        terraform init

    - name: Run Terraform Plan
      run: |
        terraform plan
