name: Terraform Plan

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull request to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: "e13ebc52-bd47-4927-a5d9-722eb7465292"
          tenant-id: "4b1732d9-fa44-47bc-ae15-1fac2dca85c6"
          subscription-id: "c57e05a2-b253-4113-8870-0bb21d04023c"

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az account show
        

    - name: Install dependencies
      run: |
        terraform init

    - name: Run Terraform Plan
      run: |
        terraform plan
      # env:
        #TF_VAR_some_variable: ${{ secrets.TF_VAR_some_variable }} # Add any sensitive variables here, if needed
        # Add other necessary environment variables here, like Azure, AWS, etc.
