name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]  # Trigger this workflow when 'Terraform Plan' workflow completes
    types:
      - completed  # Ensure it runs only after 'Terraform Plan' has completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: account-prod  # Specifies the environment where the job will run

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
    
    - name: Azure Login (User-based)
      run: |
        az login --tenant ${{ secrets.AZURE_TENANT_ID }} 

    - name: Show Azure Account
      run: |
        az account show
    
    - name: Install dependencies
      run: |
        terraform init

    - name: Run Terraform Apply
      run: |
        terraform apply -auto-approve  # Automatically approve the changes
      
