name: Terraform Plan

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull request to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
    
    - name: Azure Login (User-based)
      run: |
        az login --tenant ${{ secrets.AZURE_TENANT_ID }} 

    - name: Show Azure Account
      run: |
        az account show

    - name: Install dependencies
      working-directory: modules/account
      run: |
        terraform init -backend-config="access_key=${{ secrets.TERRAFORM_STATE_STORAGE_KEY}}"
      

    - name: Run Terraform Plan
      working-directory: modules/account
      run: |
        terraform plan
