name: Terraform Plan

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull request to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Cache Terraform providers
      uses: actions/cache@v2
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Install dependencies
      run: |
        terraform init

    - name: Run Terraform Plan
      run: |
        terraform plan
      # env:
        #TF_VAR_some_variable: ${{ secrets.TF_VAR_some_variable }} # Add any sensitive variables here, if needed
        # Add other necessary environment variables here, like Azure, AWS, etc.
